### ISSUE TITLE
After updating Syncrobit to the newest firmware it stopped working after 24hours and it's not accessibly locally

### ISSUE THREAD

**Issue by timetraveler90** [NebraLtd/helium-syncrobit#7] opened 2023-03-15 12:01 UTC
After updating the syncrobit miner with the latest FW ([2023.02.07.0-21-helium-syncrobit-2023-03-07-OpenFleet](https://github.com/NebraLtd/helium-syncrobit/releases/tag/2023.02.07.0-21-helium-syncrobit-2023-03-07-OpenFleet))
it was working ok for 24 hours and suddenly it stopped and it's not accessible anymore over local IP address, when i ping it i am getting responses from the miner but the dashboard is not opening.

Tried to re-flash it again but it's the same situation.

Could you please help me out what could be the cause of this?

**Comment by Maudslay** [comment] 2023-03-16 07:52
I can confirm this is also happening to me too, I just thought it was myself but it does seem to work for 24 hoursish then die out, Miner is still on but doesn't do anything

**Comment by larrybml** [comment] 2023-03-16 10:43
Same here, unit is working for almost 48 hours, after that you can only ping it, no web interface and no mining.

**Comment by DriftMoss** [comment] 2023-03-16 16:56
Like the others I too have 2 miners both flashed with latest v.21. Miners work for 24hrs then stop. Cannot access through dashboard via web or helium app. Is this due to migration  or what? Can we expect a new FW to be released soon?

**Comment by rpvrpv** [comment] 2023-03-16 19:24
Same issue here

**Comment by shawaj** [comment] 2023-03-16 23:17
Thanks for the reports @larrybml @timetraveler90 @Maudslay @DriftMoss @rpvrpv - much appreciated.

So we can try to reproduce the error, can you confirm you just downloaded the image from this repo and flashed to your device? Or could you explain how you did it?

**Comment by DriftMoss** [comment] 2023-03-17 01:40
Yes I downloaded the latest file from github. It worked on both my SB
miners for about 24hr then they both just stopped.

**Comment by gkiss86** [comment] 2023-03-17 05:30
Same problem here. Syncrobit V2 hotspot.
Downloaded the firmware from here. Flashed the module with CM4IO board with RPimager. Works for 2 days then stops working. Device can be pinged but dashboard cannot be opened. Tried to flash with balena too, issue still the same.
Not sure what the software is trying to do but it is always 2 days only. Looks like it gets stuck when trying to look for update or some process times out after 48 hours. No reset button, no remote access. Have to climb on the roof disassemble everything and reflash over and over again. :(

**Comment by rpvrpv** [comment] 2023-03-17 06:25
I have a syncrobit V1. Downloaded latest firmware also. Flashed using CM4IO and Balena Etcher on a windows laptop. I first noticed (using HeliumGeek) that the device stops witnessing and beaconing and than after about I day I guess the dashboard was not accessible anymore while all the time the device is visible on my network and produces some keep alive data 

![705A0E51-D91B-4592-9CA4-CAB04C263BCD](https://user-images.githubusercontent.com/128090615/225828611-cbc565a4-35d1-4ea3-95eb-db3227b5254f.jpeg)

**Comment by Dani1914** [comment] 2023-03-17 06:40
I have syncrobit v2 ,i re-flashing two times whith firmware nebra v21(latest) and working 2,days and stop,no dashboard,no whithness,in fing i dont see anymore divace nebra,just Raspberry pi,if i reflash,all back normal but just for 2 days!Whit firmware versian 19 i not have this problems but no more rewards whith this version!
B.r.
Dani

**Comment by timetraveler90** [comment] 2023-03-17 09:12
If you need any specific info, please let me know I will try my best to extract it from the miner as its once again stuck and not working @shawaj

**Comment by timetraveler90** [comment] 2023-03-17 12:37
Also have one more question, is there a chance to push the changes OTA so we do not need to update it manually all the time ?

**Comment by Maudslay** [comment] 2023-03-17 12:41
> Also have one more question, is there a chance to push the changes OTA so we do not need to update it manually all the time ?

I would like this as manually just takes time!

**Comment by KevinWassermann94** [comment] 2023-03-17 16:49
Anyone affected by this, could you please send a mail to support@nebra.com and reference this GitHub issue?
Please let us know the serial and mac address of your miners so that we can investigate

**Comment by shawaj** [comment] 2023-03-17 16:54
> Also have one more question, is there a chance to push the changes OTA so we do not need to update it manually all the time ?

@Maudslay @timetraveler90 the updates already *are* pushed OTA if you use the openfleet images. It is only if you use your own BalenaCloud account that you have to manually do updates or set up your own automations. However, to fix this issue you will probably have to reflash your device I would imagine (hard to say until it is ready)

And as mentioned by @KevinWassermann94 please send a ticket so we can check into this further.

**Comment by timetraveler90** [comment] 2023-03-17 17:19
@shawaj @KevinWassermann94 ticket #413478 is created, just sent an email from my side, please extract logs if you can so I can re-flash it to make it work again before those logs are lost

**Comment by timetraveler90** [comment] 2023-03-17 17:22
And regarding the OTA updates, I didn't receive my update from the previous version to the newest one even after 4 days of waiting so I decided to manually re-flash it again,


Do I need to subscribe to those updates somewhere or is there any additional step I need to do in order to be eligible for them?

**Comment by Maudslay** [comment] 2023-03-17 17:38
> > Also have one more question, is there a chance to push the changes OTA so we do not need to update it manually all the time ?
> 
> @Maudslay @timetraveler90 the updates already _are_ pushed OTA if you use the openfleet images. It is only if you use your own BalenaCloud account that you have to manually do updates or set up your own automations. However, to fix this issue you will probably have to reflash your device I would imagine (hard to say until it is ready)
> 
> And as mentioned by @KevinWassermann94 please send a ticket so we can check into this further.

Thanks but I have used everything that was advised and the miner has never done an OTA updates, I just had to update it every time an update came out.

**Comment by rpvrpv** [comment] 2023-03-18 06:32
What is the link for logging a ticket?

**Comment by Dani1914** [comment] 2023-03-18 12:58
This is my ticket sended on nebra support before 5 days:
Syncrobit firmware v21 stop working #413149

**Comment by charlee-dr** [comment] 2023-03-18 13:04
> What is the link for logging a ticket?
You should send a mail to support@nebra.com and reference this GitHub issue, indicating the serial number and mac address of your miner.

**Comment by shawaj** [comment] 2023-03-18 14:32
Or you can go to https://support.nebra.com

**Comment by shawaj** [comment] 2023-03-18 14:38
@Maudslay @timetraveler90 for the OTA updates and this problem, we think this is almost certainly due to our recent infrastructure migration... https://www.nebra.com/blogs/news/nebra-hotspot-infrastructure-migration

We are still trying to discover the root cause so if you can write in with further details it will definitely help us to work out what's going on.

**Comment by Maudslay** [comment] 2023-03-18 14:47
@shawaj That makes sense and  understandable that an back end infrastructure change could have caused this issue but on reproducing the issue is straightforward just flash a miner with the current firmwares with the instructions given by yourselves, leave it for 24-48 hours and then stops mining and can't access it locally either.

**Comment by sjso395** [comment] 2023-03-18 15:41
I have 3 Syncrobit v2 miners also that quit working after 2 days. Luckily, they are all still on my desk since I wanted to make sure they worked before deploying. Downloaded the firmware from here. Flashed the module with CM4IO board with RPimager also. I can ping the miner locally, but it doesnt come up. Ticket #413562 submitted.

**Comment by shawaj** [comment] 2023-03-18 19:36
Thanks @sjso395 

@Maudslay yep we can reproduce it but haven't worked out the cause yet. But thanks for your help with the info in any case. Bit of a strange issue!

**Comment by shawaj** [comment] 2023-03-19 00:40
Think I've found the cause now. Just trying to build a new image at the moment. Will keep you posted.

This should fix the OTA issue too!

**Comment by cryptoHelium** [comment] 2023-03-19 18:35
Looking forward to the release. I've tried multiple versions of the firmware and all I get now is a solid RED light on my syncrobit. Everything was working fine until March 8th.

**Comment by cryptoHelium** [comment] 2023-03-19 19:52
> I have 3 Syncrobit v2 miners also that quit working after 2 days. Luckily, they are all still on my desk since I wanted to make sure they worked before deploying. Downloaded the firmware from here. Flashed the module with CM4IO board with RPimager also. I can ping the miner locally, but it doesnt come up. Ticket #413562 submitted.

I have the SD card version and this is exactly what is happening with mine. I can ping it but doesn't come up. LED at the back is solid red.

**Comment by shawaj** [comment] 2023-03-20 00:14
Hoping to have the new release in the next couple of days. It's working fine now on my test unit but, annoyingly, our image building is now failing... https://github.com/NebraLtd/helium-syncrobit/actions/runs/4458830817/jobs/7830892342

I think I know the cause but I need someone else on our team with better knowledge of this system to check and fix it. Hopefully tomorrow, all being well 🤠

**Comment by charlee-dr** [comment] 2023-03-20 09:36
Hi @shawaj,
Once this new release is ready, do we need to manually flash the new image or will it be distributed via OTA to miners?
Thank you for your support!

**Comment by shawaj** [comment] 2023-03-20 15:00
Ok we have an image now 🥳

https://github.com/NebraLtd/helium-syncrobit/releases/tag/TEST-helium-syncrobit-2023-03-20-OpenFleet

Please try this one. It shouldn't have any issues now

Please let me know how you get on!

**Comment by shawaj** [comment] 2023-03-20 15:00
@charlee-dr yes you will need to manually flash this time. But after this flash the OTA should be fixed 👍

**Comment by sjso395** [comment] 2023-03-20 18:05
Thanks. So far this has been working great. Can get to the dashboard again and shows online. Monitoring to see what action it takes over the next 24-48 hours. Wish my other ticket was fixed this quick with Nebra. Had a ticket open since last week about Rockpi's having old FW. They responded back that they were sending custom FW, no response since . According to discord, people have been waiting weeks with the same response.

**Comment by KevinWassermann94** [comment] 2023-03-20 18:08
@sjso395 We will get that resolved asap

**Comment by shawaj** [comment] 2023-03-20 18:54
@sjso395 it is all due to the infrastructure migration we announced on our blog.

For now, you can use these images for Nebra miners...
ROCKPi:
- 868 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-indoor2-2023-03-20-868.zip
- 915 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-indoor2-2023-03-20-915.zip

RasPi Indoor:
- 868 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-indoor1-2023-03-20-868.zip
- 915 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-indoor1-2023-03-20-915.zip

RasPi outdoor:
- 868 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-outdoor1-2023-03-20-868.zip
- 915 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-outdoor1-2023-03-20-915.zip

**Comment by sjso395** [comment] 2023-03-20 19:20
Thanks again. So I dont need a specific FW for my miner ? On the Nebra page from last week , its says  "OS image file specifically for your ROCK Pi hotspot (provided by Nebra)" .  Just dont want to screw anything up.

**Comment by sjso395** [comment] 2023-03-20 19:21
> @sjso395 it is all due to the infrastructure migration we announced on our blog.
> 
> For now, you can use these images for Nebra miners... ROCKPi:
> 
> * 868 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-indoor2-2023-03-20-868.zip
> * 915 - https://storage.googleapis.com/nebra-disk-images/nebra-cloud-helium-nebra-indoor2-2023-03-20-915.zip
> 

@shawaj  Thanks again. So I dont need a specific FW for my miner ? On the Nebra page from last week , its says "OS image file specifically for your ROCK Pi hotspot (provided by Nebra)" . Just dont want to screw anything up.

**Comment by KevinWassermann94** [comment] 2023-03-20 19:56
Yeah, it's not needed anymore. These images will work universal, as long as you use the correct variant

**Comment by sjso395** [comment] 2023-03-21 16:59
@KevinWassermann94 is there a public link to these FW's that I can have so I can share it with other people with Rockpi's that wont update please?

**Comment by shawaj** [comment] 2023-03-21 17:58
@larrybml @timetraveler90 @Maudslay @gkiss86 @Dani1914 @DriftMoss @charlee-dr @cryptoHelium @rpvrpv @sjso395 

How's the new Syncrobit image working for you?

**Comment by shawaj** [comment] 2023-03-21 18:00
@sjso395 you can share these links publicly. They will also be available in the releases section of the repos soon.

One thing to note, the images I shared are our manufacturing images... So you will need to boot them up once, leave them for about 15 minutes, remove the power and then reboot. Otherwise the diagnostics page will not work.

The ones coming to the repo shortly, will not have this restriction and will work straight away.

**Comment by Maudslay** [comment] 2023-03-21 18:02
> @larrybml @timetraveler90 @Maudslay @gkiss86 @Dani1914 @DriftMoss @charlee-dr @cryptoHelium @rpvrpv @sjso395
> 
> How's the new Syncrobit image working for you?

I flashed it this moment in a rush before work and 3 hours ago UK Time I'm beaconing which is a good sign but I will report back in 2 to 3 days to see if it drops offline again. Thanks for getting this sorted quickly.

**Comment by timetraveler90** [comment] 2023-03-21 18:03
I didnt have time to flash it these days, in the next hour or two I am planning to finish with it and I will keep you posted about it.

Thanks for really quick solution guys, appreciate it

**Comment by shawaj** [comment] 2023-03-21 18:12
Awesome. Thanks for the feedback and glad it seems to be working well. We have lots of new improvements coming through including multi-mining and Nebra dashboard support among other things.

If you have found our open source firmware useful we would be super grateful if you would consider sponsoring our efforts at the below link. This will be really helpful to us, in order to keep supporting all the 3rd party vendors...

https://github.com/sponsors/NebraLtd

**Comment by charlee-dr** [comment] 2023-03-22 17:47
> @larrybml @timetraveler90 @Maudslay @gkiss86 @Dani1914 @DriftMoss @charlee-dr @cryptoHelium @rpvrpv @sjso395 
> 
> How's the new Syncrobit image working for you?

After more than 48 hours of good PoC performance I confirm it's working properly so far. Let's hope it continues rocking. 

Thank you for your support 🦾

**Comment by shawaj** [comment] 2023-03-22 21:33
Awesome, thanks @charlee-dr for taking the time to post the results. Good to know it's still working well and appears to be fixed 🙏

I'll close this issue now, but feel free to open a new one if this happens again.

And don't forget to donate some funds 😉 https://github.com/sponsors/NebraLtd

**Closed as completed by shawaj** 2023-03-22 21:33 UTC

**Comment by timetraveler90** [comment] 2023-03-22 23:08
Yep, everything is great so far.

Thanks once again guys!

**Comment by joaopaulo529** [comment] 2023-03-28 23:35
I have some questions..  I flashed several syncrobits that I have in total, I have more than 10 .. but I flashed them and I already went to install them again in the places .. but of the 4 that I installed 2 stopped 12 days ago 😔 the new firmware that nebra made will not be automatic installed?  or will I have to go and reflash the 10 equipment again?  I do not know what to do.  the names of these 2 devices that stopped are (Blunt Hickory Gorilla) and (Short Tartan Coyote) I still need to see the others.. but for now I have these already installed that stopped.. the other 2 that I installed and are working are called ( Unique Aquamarine Cougar) and (Amateur Fuchsia Osprey)

**Comment by shawaj** [comment] 2023-03-29 00:07
@joaopaulo529 you need to be on either the image linked here:
- https://github.com/NebraLtd/helium-syncrobit/issues/7#issuecomment-1476391321

Or a newer one:
- https://github.com/NebraLtd/helium-syncrobit/releases/tag/2023.02.07.0-25-helium-syncrobit-2023-03-27-OpenFleet
- https://github.com/NebraLtd/helium-syncrobit/releases/tag/2023.02.07.0-26-helium-syncrobit-2023-03-28-OpenFleet

Them you will get the OTA. 

If you are on the 2023.02.07.0-21 or earlier release you will probably have issues.
